package com.pulseops.incident;

public enum TimelineEventType {
	INCIDENT_CREATED,
	STATUS_CHANGED,
	SEVERITY_CHANGED,
	ASSIGNED,
	UNASSIGNED,
	COMMENT_ADDED,
	SERVICE_RECOVERED,
	INCIDENT_RESOLVED,
	ROOT_CAUSE_UPDATED,
	RESOLUTION_UPDATED
}
