package com.pulseops.liveevent;

public enum LiveEventType {
	CONNECTION_READY,
	SERVICE_CREATED,
	SERVICE_UPDATED,
	SERVICE_DELETED,
	SERVICE_STATUS_CHANGED,
	HEALTH_CHECK_RECORDED,
	INCIDENT_CREATED,
	INCIDENT_UPDATED,
	INCIDENT_COMMENT_ADDED,
	NOTIFICATION_CREATED
}
